server:
  port: 8081

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:book}"
    username: "${POSTGRES_USER:postgres}"
    password: "${POSTGRES_PWD:admin}"
  jpa:
    show-sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog-master.xml
    enabled: true
    drop-first: true
  kafka:
    producer:
      bootstrap-servers: "${SPRING_KAFKA_SERVER:localhost}:${SPRING_KAFKA_SERVER_PORT:9092}"
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: abc.service2.serializer.BookEventSerializer
    consumer:
      bootstrap-servers: "${SPRING_KAFKA_SERVER:localhost}:${SPRING_KAFKA_SERVER_PORT:9092}"
      auto-offset-reset: earliest
      group-id: book-service2
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: abc.service2.deserializer.BookEventDeserializer
