spring:
  data:
    mongodb:
      uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"
      database: "${MONGO_DB:books}"
  kafka:
    producer:
      acks: all
      bootstrap-servers: "${SPRING_KAFKA_SERVER:localhost}:${SPRING_KAFKA_SERVER_PORT:9092}"
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: pl.abc.service1.serializer.BookEventSerializer
