spring:
  data:
    mongodb:
      uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"
      database: "${MONGO_DB:books}"
kafka:
  bootstrap-servers: "${KAFKA_SERVER:localhost}:${KAFKA_SERVER_PORT:9092}"
